### ISSUE TITLE
バグ報告

### ISSUE THREAD

**Issue by kotetsu32559** [incompetence33/uma_sh#10]
あまりgithubのようなものを触ったことがないので、バグ報告するべきかそれとも改善案にするべきかどうか悩んだのですがこちらで報告させていただきます。

**バグの内容**
vgmstreamが、最新版だとファイル名が変わっているようで、./uma.shを何度行ってもcurlがno URL specifiedとなってしまってダウンロードできず、「vgmstreamがないようです」というようなメッセージが表示されてしまう。

**解決方法と思われるもの**
そこでuma.shの中のvgmstream-cli.zipという部分を全て最新版のファイルのvgmstream-cli-linux.zipに置換したところ、今のところはうまくいっているので報告させていただきました。

先ほどuma.shのために初めてwslを使い始めた初心者中の初心者なので解決方法が正しいかどうかはわかりません。vgmstream-cli-linux.zipがvgmstream-cli.zipの代わりとして合っているのかもわかりませんが、原因自体はおそらく上記のようにファイル名が変わってしまったことだと思いますので、あとは経験者様にお任せします…。

**Comment by incompetence33** [comment]
報告ありがとうございます。
ご指摘の通りvgmstreamのファイル名が変更されていたようです。
修正方法ですがご提示頂いた方法で合っています。
こちらでも同じように修正させていただきました。

このようなファイル名の変更は気が付きにくいので発見した場合issueしていただけるととても助かります。
こちらの不手際でご迷惑おかけしました。
