### ISSUE TITLE
バグ報告

### ISSUE THREAD

**Issue by rinjoya** [incompetence33/uma_sh#12]
**バグの内容**
acb,awbファイルが正しく変換されていない

**バグの発生条件**
発生手順:
1. uma.shを起動し、ライブ音声を保存
2. acbやawbファイルをコピーしているという表示がある。
3. 変換が終了してsound_wavフォルダを見ても、目的のmp3フォルダがない。
4. soundフォルダの方には存在している。

**環境**
 - OS: windows11
 
**補足**
![image](https://github.com/incompetence33/uma_sh/assets/103830075/2dfee74b-ce4b-4508-ba4b-dcdc463a450b)
![image](https://github.com/incompetence33/uma_sh/assets/103830075/85c60acf-0ed1-4e3a-854b-1b3529efbed2)
![image](https://github.com/incompetence33/uma_sh/assets/103830075/443fe1e8-5071-464b-9ee3-24ca8a6f0f6e)
また、sound_wav内のlフォルダ以外は更新されている(中身はすべて空)が、lフォルダだけ更新日時が過去のままである。
![image](https://github.com/incompetence33/uma_sh/assets/103830075/8c5e675c-d1bf-4efc-8e26-c2bd23f5f1df)

**Comment by incompetence33** [comment]
uma.shはアセットをダウンロードする機能がないのでゲームの方で先にデータダウンロードする,サーバーから直接ダウンロードするプログラムを使うなどして新しいデータを取得しなければ更新はされません。
また、mataファイルは一度ゲームを起動(ロビー画面までいけばOK)しなければ更新されないのでそのせいかもしれません。

こちらの環境で実行してみたところ、問題なく動作したので上記のような原因でうまくいっていない可能性が高いです。
データダウンロード、ロビー画面までゲームを起動してもうまくいかない場合はまた詳しい状況を教えてください。

**Comment by rinjoya** [comment]
一括データダウンロードとロビー画面の表示を行いましたが、改善されませんでした。
個人的、soundフォルダにはあるのにsound_wavフォルダにないのが気になっています。

**Comment by incompetence33** [comment]
ちょっと見てみたのですが、1084だけvgmstream-cliがエラーを出して変換できませんでした。
```log
AWB: unknown codec (report)
failed opening snd_bgm_live_1001_chara_1084_01.awb
```
vgmstreamを最新にしてみましたがうまくいかなかったのでちょっとなんでか分からなかったです。無能で申し訳ない。

**Comment by rinjoya** [comment]
なるほど...その場合は別の変換ソフトで変換すればいいでしょうか
