### ISSUE TITLE
uma_pic.shが使えない

### ISSUE THREAD

**Issue by N4SH1** [incompetence33/uma_sh#14]
![image](https://github.com/incompetence33/uma_sh/assets/112229698/099dad35-fa37-44f9-83c5-ecb6ca3448b3)

公式サイトがリニューアルされてからかもしれませんが、使えなくなっていました。
こちらの環境のせいかもしれませんので一度確認していただけませんか…？

**Comment by incompetence33** [comment]
確かに使えなくなっていますね……
https://github.com/incompetence33/uma_js
こちらに新しく同じ機能をもった「uma_pic.js」を追加しました。
よろしければこちらを使ってみてください。

**Comment by N4SH1** [comment]
迅速な返信ありがとうございます！
これを機にuma.jsの方を導入してみたのですが、無事すべての画像が保存されました！
本当に無知なのでvgmstreamのPATHを通すという作業に苦戦しましたが、無事成功して音声も抽出出来て大満足です。
本当にありがとうございました。
これからも応援してます！
