### ISSUE TITLE
ファイルの仕分けについて

### ISSUE THREAD

**Issue by Nehalem1156** [incompetence33/uma_sh#3]
「全て」を選択したときにディレクトリも復元をするかしないかの選択を出してほしいです
ディレクトリが復元されたファイルがすべて欲しいときに選択したアセットから一つ一つやってると日が暮れてしまうので…

**Comment by incompetence33** [comment]
issueしてくれてありがとうございます。
修正しました。
スレの方で出てた並列処理の問題も解決しておきました。

**Comment by Nehalem1156** [comment]
ありがとうございます！

**Comment by Nehalem1156** [comment]
メール、気づきませんでした。今更ながらありがとうございます(ツールの更新は知っていました、使わせていただいています)
スレでは荒らしがいろいろ言ってましたが、私のような情弱でも簡単にぶっこぬけるツールを提供してくださる方はそうそういません。ユーザーフレンドリーでとても助かっております。本当にありがとうございます。

2022年2月27日(日) 22:13 incompetence33 ***@***.***>:
