### ISSUE TITLE
uma.shの質問（初心者）

### ISSUE THREAD

**Issue by DOTsan999** [incompetence33/uma_sh#4]
連絡失礼します。uma.shについて調べても自力でうまく行かない部分があります。
![スクリーンショット (8)_LI](https://user-images.githubusercontent.com/89884252/160229072-dcd3191b-fa49-4a45-b974-bec72fd19c02.jpg)
この画像の状態を解消するにはどのようなことをすればいいのでしょうか？setupは起動させています。

**Comment by incompetence33** [comment]
スクリプトの実行の仕方が間違ってますね。その方法だとBornShellというShellで実行されてしまうので上手くいっていないといった感じです。
なので
```sh
./uma.sh
```
ってやればOKです。
見たところSetupも正常にできていないようなので
```sh
./setup.sh
```
でもう一度やり直してみて下さい。
あと
```sh
./uma.sh -j30 -s20
```
のように実行すると処理を並列で実行するので速く終わらせることができます(jの後の数字はファイルコピーの並列数で、sは音声デコードの並列数です)。

**Comment by DOTsan999** [comment]
教えていただいたとおりに入力したらあっという間に抽出できました！とても基礎的なことでしたが回答していただき、ありがとうございます。
