### ISSUE TITLE
使い方がわからない

### ISSUE THREAD

**Issue by ilte123** [incompetence33/uma_sh#5]
**わからなかったこと**
setup.shが実行できない

**試したこと**
setup.shを指定して実行

**環境**
- OS: win10
![無題](https://user-images.githubusercontent.com/103738522/163552766-e69c4ab1-b71b-4ef9-b3c8-691d9cbf3f1c.jpg)
当方、WSL導入は初めてです。

**補足**
スクショの表記が出て、初期の設定ができません。
なにかきーを
無視してuma.shを実行しようとすると、umamusumeフォルダに入れて実行して下さいと言われます。
アドバイスいただけないでしょうか？
初歩的な質問で申し訳ございません。

**Comment by incompetence33** [comment]
Setupの全工程を自動でやるように改良しました。
下のコマンドを実行すればできると思います。
```sh
bash <(curl -sL "$(curl -sL "https://github.com/incompetence33/uma_sh/releases/latest/"|grep -E '<a.*\/setup_ubuntu_zsh.sh" rel'|awk -F'["]' '{printf "https://github.com%s",$2}')")
```
uma.shが実行できないとのことですが、おそらくuma.shが
/mnt/c/Users/ユーザ名/AppData/LocalLow/Cygames/umamusume
にないことが考えられます。
もしくは自信がそのディレクトリにいないことですかね。
```sh
pwd -P
```
と実行して
/mnt/c/Users/ユーザ名/AppData/LocalLow/Cygames/umamusume
にいないようでしたらそこへ移動してみて下さい。
また何かわからないことがあれば連絡して下さい。

**Comment by ilte123** [comment]
ご対応ありがとうございます。
実行した見たところ、以下のようになりました。

$ bash <(curl -sL "$(curl -sL "https://github.com/incompetence33/uma_sh/releases/latest/"|grep -E '<a.*\/setup_ubuntu_zsh.sh" rel'|awk -F'["]' '{printf "https://github.com%s",$2}')")                                これは簡易的な環境構築スクリプトです。                                                                                  Wslをインストールしてこれから環境を0から作らなければいけない方向けのスクリプトです。                                    これを実行するとログインShellはZshになります。                                                                          oh-my-zshやPreztoみたいなものは導入しません。                                                                           それでも最低限使っていけるようにはなっていますが各々カスタマイズして使いやすいようにしてください。                      あ、vimもインストールするので拒否反応が出る方は後でアンインストールしておいてください。                                 途中何回かパスワードを求められると思いますが、全てUbuntuをインストールしたときに決めたものを入力すればOKです。          よろしければなにかキーを押してください。                                                                                /dev/fd/63: line 16: unzip: command not found                                                                           zshrc と myfunctionsがこのスクリプトと同じ階層にありません。                                                            自分でちゃんと.zshrcくらい作ってる！って方はこのスクリプトの9行目をコメントアウトか削除してください。

**Comment by incompetence33** [comment]
```sh
bash <(curl -sL "$(curl -sL "https://github.com/incompetence33/uma_sh/releases/latest/"|grep -E '<a.*\/setup_ubuntu_zsh.sh" '|awk -F'["]' '{printf "https://github.com%s",$2}')")
```
すみません。これでできるようになったかと思います。確認不足で申し訳ございませんでした。

**Comment by ilte123** [comment]
![無題02](https://user-images.githubusercontent.com/103738522/163666058-6c8f6172-ea50-40bd-aa99-2ef5c4ce2379.jpg)
早速のお返事ありがとうございます。
ただ、上記を実行しても、画像のように同じエラーが出ます。
何かが間違っているのか、もしくはもうおま環でしょうか？

**Comment by ilte123** [comment]
大変失礼しました。
unzipをインストールしていないのが原因だったんですね。
初歩の初歩でご迷惑おかけして申し訳ございませんでした。

**Comment by ilte123** [comment]
![無題3](https://user-images.githubusercontent.com/103738522/163667182-f17c45e4-d38f-49e5-91a5-3e69c946d86f.jpg)
連投して申し訳ございません。
ファイルの場所が違うみたいなのですが、どこが正しいのでしょうか？

**Comment by incompetence33** [comment]
すみません、初期環境にunzipが入ってないのは盲点でした……
そのエラーは
```sh
cd /mnt/c/Users/ユーザ名/AppData/LocalLow/Cygames/umamusume
```
するか、uma.shが置いてあるフォルダで「Shift+右クリック」で出てくる「この場所でLinux Shellを開く」を押してあげると実行できます。

**Comment by ilte123** [comment]
ありがとうございます。
実行は出来たのですが、環境セットアップが出て、画像の状態で止まってしまいます...
![無題4](https://user-images.githubusercontent.com/103738522/163692007-4bda0510-eac0-4bc1-9d5b-fe0e87e9a9a6.jpg)

**Comment by incompetence33** [comment]
スクリプトのアップデートは自動で反映されないので
```sh
./uma.sh -U
```
と入力してアップデートするとうまくいくかもしれません。

**Comment by ilte123** [comment]
アップデートも試しましたが、うまくいきません,,,

毎度、
環境:Ubuntu
vgmstream-cliコマンドがないようです。
~/commands/binにvgmstreamをビルドしてインストールします。
よろしいですか?[Y/n]:y   

となります。そしてyで環境構築を進めるとひとつ前の画像の状態となり、
umamusumeフォルダに、「vgmstream-cli.zip」というファイルが出来ています。
このzipが解凍できていないのが原因でしょうか？

**Comment by incompetence33** [comment]
展開できてないのですか？
なんででしょうかね……こちらでは上手く行ってるようなので再現できないのでわからないです……
```sh
ls ~/commands/bin/vgmstream-cli
```
でnot foundと出るようでしたら展開できていなくて、ファイルが有るならば
```sh
chmod 777 ~/commands/bin/vgmstream-cli
```
と実行してみて下さい。
お手数おかけします。

**Comment by ilte123** [comment]
(=^^=)$ ls ~/commands/bin/vgmstream-cli
ls: '/home/〇〇/commands/bin/vgmstream-cli' にアクセスできません: そのようなファイルやディレクトリはありません                                                                                                                              ~                                                                                                                       (-_-;)$                                                                                                                            

これは展開できないということでしょうか？
どこが間違っているのか教えていただけないでしょうか？

**Comment by ilte123** [comment]
連投すみません。
私も詳しくないのでわかりませんが、途中、wget : URL,がありませんとなっている部分があるので、そこが原因ではないでしょうか違ったらすみません。

**Comment by incompetence33** [comment]
![image](https://user-images.githubusercontent.com/89658872/163712154-eea0c370-7ab2-4fab-8c61-1c23e72e2aaf.png)
wgetが失敗しているのは、今どうやらvgmsetremのサイトがダウンしているらしくそれがエラー出力されていて、その処理が失敗したときにvgmstreamのGitHubからダウンロードするという処理になっているのです。
もしどうしてもうまくいかないようでしたら
```sh
curl -Lo vgmstream-cli.zip "$(curl -sL 'https://github.com/vgmstream/vgmstream/releases/latest' |grep /vgmstream-cli|awk -F'["]' '{printf "https://github.com%s\n",$2}')"
unzip -d ~/commands/bin vgmstream-cli.zip
rm -f vgmstream-cli.zip
chmod 777 ~/commands/bin/vgmstream-cli
```
を手動で実行してみて下さい。

**Comment by ilte123** [comment]
ありがとうございます！
上記のコードを実行したのちにuma.shを実行したところ、無事処理が進みました。
最初から最後まで本当にありがとうございました。m(_ _)m
![無題5](https://user-images.githubusercontent.com/103738522/163712612-1cb199d2-b80a-4202-af8c-9308edf367c7.jpg)

**Comment by incompetence33** [comment]
実行するときに
```sh
./uma.sh -j30 -s20
```
のようにすると並列処理ができ、時間短縮になるので試してみて下さい(jの後の数字がファイルコピーの並列数、sの後の数字が音声デコードの並列数です)。
こちらこそ素早く解決できず申し訳ありませんでした。
