### ISSUE TITLE
使い方がわからない

### ISSUE THREAD

**Issue by rinjoya** [incompetence33/uma_sh#6]
**わからなかったこと**
動画は
-b 0000450D -a 608C479F
でできるので頑張ってください。

**試したこと**
./uma.sh -b 0000450D -a 608C479F

**環境**
- OS: Windows11

**補足**
なにかあれば(添付したスクショの説明など)
音声の抽出などは問題なくできましたが、"動画は-b 0000450D -a 608C479Fでできるので頑張ってください。"の意味がわかりませんでした。

アドバイスいただけますと幸いです。

![image](https://user-images.githubusercontent.com/103830075/186579760-1fb98f78-8e9d-416e-ab10-2862c145ec60.png)

**Comment by incompetence33** [comment]
それは「CRID(.usm)分離ツール」というもので使う鍵の話です。
説明が足りてませんでした。申し訳ないです。
「CRID(.usm)分離ツール」は5chのどこかに転がっているので頑張って見つけて見てください。
ただ、動画は大したものが入っていないのでどうしても必要じゃない限りやらなくてもいいかもしれません。
