### ISSUE TITLE
音声ファイル(wav)が出力されない

### ISSUE THREAD

**Issue by N4SH1** [incompetence33/uma_sh#7]
**わからなかったこと**
soundフォルダやほかのフォルダには正常にファイルが抽出されましたが、
sound_wavの中はフォルダ分けされているだけでwavファイルが一つも出力されませんでした。
![1](https://user-images.githubusercontent.com/112229698/187014500-346f80ee-2133-4003-b6c9-4ac699367b56.png)
![2](https://user-images.githubusercontent.com/112229698/187014505-4fdbd2e7-fb26-40d6-b68f-c507686431bb.png)

**試したこと**
![image](https://user-images.githubusercontent.com/112229698/187014317-a0b7a2ec-cb4f-43f5-a253-388c65aed8d9.png)

Ubuntu on Windows
→「cd /mnt/c/Users/xxx/AppData/LocalLow/Cygames/umamusume/」
→「./uma.sh -j30 -s20」

「全部」を選んでも「音声のみ」を選んでも、soundフォルダ内のファイルは正常に抽出されますが、
sound_wavの中はフォルダ分けされているだけでwavファイルが一つも出力されませんでした。

処理中は一瞬で終わって処理が正常に行われていないような挙動はなく、音声のみの場合は4分程度の時間がかかってエラーなく終了します。

元データはちゃんと出力されてwav変換に失敗しているということは、vgmstreamあたりの問題なのでしょうか？

何かしらの問題で別のフォルダに出力されている説も考えましたが、1.5周年楽曲が追加されてから抽出した結果、当該フォルダに新しいライブフォルダが出力されていたので違いました。

Windows11、WSLのUbuntu環境です。
Ubuntuの環境構築用スクリプトも./uma.sh -Uも実行済みです。

旧PCではmsys2環境でうまく出力できていたのですが、新ＰＣになりせっかくならWSL環境でと思い導入し失敗したので、最悪msys2環境でも試してみればよいですかね？
もし解決が難しそうであれば外部ツールなどでwavに変換できればそれでも問題ないです。
申し訳ありませんが、ご教授いただけると助かります。

**環境**
- OS: Windows 11 Home
- WSL2 Ubuntu

**Comment by incompetence33** [comment]
こちらでは再現ができなかったので原因がわかりませんが、おっしゃる通りvgmstreamが怪しいかと思います。
```sh
rm -f "$(where vgmstream-cli)"
```
と実行して一度vgmstreamを削除してみてください。
もしそれでもだめなら適当なawbをvgmstreamに食わせてwavファイルが出力されるか試してみてください。

**Comment by N4SH1** [comment]
`rm -f "$(where vgmstream-cli)"`を実行したり再起動したり、sound_wavフォルダを消してみるなどのことをしてみましたが、症状を改善させることはできませんでした。
しかしvgmstreamを別途ダウンロードし、awbをexeにドロップすることで一括で変換できたので、しばらくはこの手法で変換していこうと思います！

**Comment by incompetence33** [comment]
```sh
vgmstream-cli hogehoge.awb
```
でwavが出力されないならvgmstreamがおかしくて、wavが出力されるならスクリプトがおかしいんですよね。
こちらでも再現できないか試してみます。
力になれず申し訳ないです。

**Comment by N4SH1** [comment]
以下の手順で治りました。やはりビルドの際にどこかで不具合が起きていたようです…。（僕には何が書いてあるかさっぱりなので、一応画像をつけておきます。）

1. Ubuntu自体をアンインストールし、再インストール
2. setup_ubuntu_zsh.shを実行し、uma.sh -Uを実行
![3](https://user-images.githubusercontent.com/112229698/187026234-bca0b699-1923-4ec6-9b1d-5f2a941324f7.png)
![4](https://user-images.githubusercontent.com/112229698/187026263-c6568649-7711-4781-981d-8c1a0aec8694.png)
3. ./uma.sh -j30 -s20で音声を抽出
![image](https://user-images.githubusercontent.com/112229698/187026199-d5294f5e-576b-46b2-b7e9-ac27c920534f.png)

再インストールという力業で解決し、結局原因がよくわかりませんでしたが、恐らくコードがおかしいとかではなくただこちらの環境構築・インストールの仕方が悪かったみたいです。申し訳ございませんでした。

迅速な対応ありがとうございました。これからも開発応援してます。
