### ISSUE TITLE
使い方がわからない

### ISSUE THREAD

**Issue by mhr1132** [incompetence33/uma_sh#8]
**わからなかったこと**
その内容

「vgmstream-cliコマンドがないようです。」となり、Yを押して続行しインストールするも、何度試行しても同じ文言が表示されてしまう。

**試したこと**
その内容

WSL導入後、環境構築（等おまけ）フォルダ内のsetup_ubuntu_zsh.shを使用してセットアップした。その後説明通りumamusumeディレクトリ内に移動して./uma.shとし実行した。しかし、「vgmstream-cliコマンドがないようです。~/commands/binにvgmstreamをインストールします。」と表示されたため、「Y」を入力した。そしてスクショのようになったあと、「環境のセットアップが済んでいましたら、もう一度スクリプトを実行し直してください。」と表示された。その後何度も./uma.shを実行したが同じ文言が表示されてしまう。

**環境**
- OS: Windows11 22H2 WSL ubuntu

**補足**
なにかあれば(添付したスクショの説明など)

・リンク先にアクセスできていないのでしょうか・・・
・WSLおよびUbuntuはあまり触ったことがないのですが、見様見真似で自分でvgmstreamのソースコードをダウンロードして展開した後、vmコマンドを用いて~/commands/binにそれを移動してみましたが状況は変わらずでした。
・ご回答宜しくお願い致します。また、不足情報ありましたら何なりとお申し付けください。
![image](https://user-images.githubusercontent.com/115158369/194311365-93f9406d-48c4-4acd-91e2-4686e54db9de.png)

**Comment by incompetence33** [comment]
今見てみたところ、vgmstreamのダウンロード先が変わっていてうまくいかなくなっていたようです。
修正しましたので、
```sh
./uma.sh -U
```
と実行し、アップデートしてから再度お試しください。

余談ですが、添付のスクショを見てみたところ「root」ユーザーでログインしてしまっているようです。
「su」コマンドを実行していませんか？そうであれば通常ユーザーで実行してみてください。
もしsuコマンド実行していなくてその状態であれば、ユーザーの作成に失敗していると思うのでユーザーを作るかwslをインストールし直してみてください。

対応が遅れてしまい申し訳ございません。

**Comment by mhr1132** [comment]
ありがとうございます！無事まとめる事ができました！
たしかに、rootユーザーとして実行されているようですが、問題なく作動しました。潜在的な問題があるのでしょうか？

**Comment by incompetence33** [comment]
スーパーユーザーのままだと削除したらまずいファイルを削除できてしまったり、一部コマンドを実行できなかったりします。
なにか特別な理由がない限り通常ユーザーにしておくのが無難です。
