### ISSUE TITLE
vgmstream-cliが反応しない

### ISSUE THREAD

**Issue by Lilithfast** [incompetence33/uma_sh#9]
**わからなかったこと**
ライブ音声を解析して出していたんですが、動画のような状態になってしまってacbは出るんですがwav変換ができません
調べてみた感じpathがつながっていないっぽい？と思っていろいろ試してみたのですがダメでした
vgmstream-cli自体は存在してます

**試したこと**
zshrcやprofileに記述してみる
export PATH = $PATH:"追加したいファイルのパス"
上を一番下に記述した

**環境**
- OS: win10 home
Ubuntu
リリースのとこに書いてあったコマンドを実行

![screenshot2023_1_14_22_53_49](https://user-images.githubusercontent.com/65488719/212475493-0b5e7f98-62fb-49f4-b479-ebe706b68908.png)

**Comment by incompetence33** [comment]
bcコマンドがないとあるので、
```sh
apt install bc
```
上記のコマンドを実行してbcコマンドインストールしてやればうまくいくかと思います。
お手数かけます。

**Comment by Lilithfast** [comment]
![screenshot2023_1_15_3_24_53](https://user-images.githubusercontent.com/65488719/212489776-2ea43c4f-9e4d-4f55-aa46-7651c4c10b50.png)
解決しました
初歩的な問題だったようで、こちらこそ申し訳ないです
